using Newtonsoft.Json;
using TypeSharp;
using Xunit;

namespace Ajax.Tests
{
    public class JSendTests
    {
        public struct Model
        {
            public string ABC { get; set; }
        }

        [Fact]
        public void GeneralTest()
        {
            Test(JSend.Success());
            Test(JSend.Fail());
            Test(JSend.Error("error message"));
            Test(JSend.Error("error message", "#0"));
            Test(JSend.Success(new Model { ABC = "\"abc\"" }));
            Test(JSend.Fail(new Model { ABC = "\"abc\"" }));
            Test(JSend.Error("error message", "#0", new Model { ABC = "\"abc\"" }));
        }

        [Fact]
        public void JSendTest()
        {
            Test((JSend)JSend.Success());
            Test((JSend)JSend.Fail());
            Test((JSend)JSend.Error("error message"));
            Test((JSend)JSend.Error("error message", "#0"));
            Test((JSend<Model>)JSend.Success(new Model { ABC = "\"abc\"" }));
            Test((JSend<Model>)JSend.Fail(new Model { ABC = "\"abc\"" }));
            Test((JSend<Model>)JSend.Error("error message", "#0", new Model { ABC = "\"abc\"" }));
        }

        [Fact]
        public void StatusTest()
        {
            Assert.True(JSend.Success().IsSuccess());
            Assert.False(JSend.Success().IsFail());
            Assert.False(JSend.Success().IsError());

            Assert.False(JSend.Fail().IsSuccess());
            Assert.True(JSend.Fail().IsFail());
            Assert.False(JSend.Fail().IsError());

            Assert.False(JSend.Error("").IsSuccess());
            Assert.False(JSend.Error("").IsFail());
            Assert.True(JSend.Error("").IsError());
        }

        [Fact]
        public void TypeSharpTest()
        {
            var typeSharpVersion = typeof(TypeScriptModelBuilder).Assembly.GetName().Version;
            var builder = new TypeScriptModelBuilder();

            builder.CacheType(typeof(JSend<>));
            builder.AddDeclaredType(typeof(JSend), "JSend<any>");

            var code = builder.Compile();
            Assert.Equal($@"/* Generated by TypeSharp v{typeSharpVersion} */

declare namespace Ajax {{
    interface JSend<TData> {{
        status?: string;
        code?: string;
        message?: string;
        data?: TData;
    }}
}}
", code);
        }

        private void Test(JSend jsend)
        {
            var clone = JsonConvert.DeserializeObject<JSend>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
            Assert.Equal(jsend.Code, clone.Code);
            Assert.Equal(jsend.Message, clone.Message);
        }
        private void Test<TData>(JSend<TData> jsend)
        {
            var clone = JsonConvert.DeserializeObject<JSend<TData>>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
            Assert.Equal(jsend.Code, clone.Code);
            Assert.Equal(jsend.Message, clone.Message);
        }

        private void Test(JSuccess jsend)
        {
            var clone = JsonConvert.DeserializeObject<JSuccess>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
        }
        private void Test<TData>(JSuccess<TData> jsend)
        {
            var clone = JsonConvert.DeserializeObject<JSuccess<TData>>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
        }

        private void Test(JFail jsend)
        {
            var clone = JsonConvert.DeserializeObject<JFail>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
        }
        private void Test<TData>(JFail<TData> jsend)
        {
            var clone = JsonConvert.DeserializeObject<JFail<TData>>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
        }

        private void Test(JError jsend)
        {
            var clone = JsonConvert.DeserializeObject<JError>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
            Assert.Equal(jsend.Code, clone.Code);
            Assert.Equal(jsend.Message, clone.Message);
        }
        private void Test<TData>(JError<TData> jsend)
        {
            var clone = JsonConvert.DeserializeObject<JError<TData>>(JsonConvert.SerializeObject(jsend));
            Assert.Equal(jsend.Status, clone.Status);
            Assert.Equal(jsend.Data, clone.Data);
            Assert.Equal(jsend.Code, clone.Code);
            Assert.Equal(jsend.Message, clone.Message);
        }

    }
}
